defineModule(sim, list(
  name = "caribouNN",
  description = "Performs an experiment on models with different forecasting settings",
  keywords = "",
  authors = structure(list(list(given = "Tati", family = "Micheletti", role = c("aut", "cre"), 
                                email = "tati.micheletti@gmail.com", comment = NULL)), 
                      class = "person"),
  childModules = character(0),
  version = list(caribouNN = "0.0.1"),
  timeframe = as.POSIXlt(c(NA, NA)),
  timeunit = "year",
  citation = list("citation.bib"),
  documentation = list("NEWS.md", "README.md", "caribouNN.Rmd"),
  reqdPkgs = list("SpaDES.core (>= 3.0.4)", "ggplot2","data.table", "torch", "luz", 
                  "future", "future.apply"),
  parameters = bindrows(
    #defineParameter("paramName", "paramClass", value, min, max, "parameter description"),
    defineParameter(".plots", "character", "screen", NA, NA,
                    "Used by Plots function, which can be optionally used here"),
    defineParameter(".plotInitialTime", "numeric", start(sim), NA, NA,
                    "Describes the simulation time at which the first plot event should occur."),
    defineParameter(".plotInterval", "numeric", NA, NA, NA,
                    "Describes the simulation time interval between plot events."),
    defineParameter(".saveInitialTime", "numeric", NA, NA, NA,
                    "Describes the simulation time at which the first save event should occur."),
    defineParameter(".saveInterval", "numeric", NA, NA, NA,
                    "This describes the simulation time interval between save events."),
    defineParameter(".studyAreaName", "character", NA, NA, NA,
                    "Human-readable name for the study area used - e.g., a hash of the study",
                          "area obtained using `reproducible::studyAreaName()`"),
    ## .seed is optional: `list('init' = 123)` will `set.seed(123)` for the `init` event only.
    defineParameter(".seed", "list", list(), NA, NA,
                    "Named list of seeds to use for each event (names)."),
    defineParameter(".useCache", "logical", FALSE, NA, NA,
                    "Should caching of events or module be used?"),
    defineParameter("epoch", "numeric", 50, 10, 100, 
                    "Epochs for the ranking model (keep low for speed)"),
    defineParameter("batchSize", "numeric", 128, 32, 4096, 
                    "Batch size"),
    defineParameter("learningRate", "numeric", 0.01, 0.001, 0.1, 
                    paste0("Learning rate. The smaller it is, the longer it takes, but the more",
                           " precise to find the best parameters.")),
    defineParameter("reRunModels", "logical", FALSE, NA, NA,
                    "Should the models be re-run?"),
    defineParameter("rerunTraining", "logical", FALSE, NA, NA,
                    "Should the training be re-run?"),
    defineParameter("reRunDataset", "logical", FALSE, NA, NA,
                    "Should the dataset saving be re-run?"),
    defineParameter("useFuture", "logical", TRUE, NA, NA,
                    paste0("Should the package future be used for paralellizing?",
                          " Only worth it in large machines!")),
    defineParameter("useSavedPlan", "logical", TRUE, NA, NA,
                    paste0("Should the module use a saved plan or recreate it?")),
    defineParameter("modComplex", "character", "all", NA, NA,
                    paste0("Which model complexity should the module run? Defaults to 'all', which",
                           "means it will run all models. This was added to help paralellize more ",
                           "quicky and have better control of the runs.")),
    defineParameter("maxClu", "numeric", Inf, NA, NA,
                    paste0("How many cores should we use at maximum?",
                           "Deafults to all avaliable. NOTE: This may cause problems with C++ during ",
                           "model fitting. Ideally, go about 10% less than the available number of ",
                           "cores."))
  ),
  inputObjects = bindrows(
    expectsInput("featurePriority", "character", 
                  "Ordered list of variable names based on importance")
  ),
  outputObjects = bindrows(
    createsOutput(objectName = "experimentPlan", objectClass = "data.table", 
                  desc = paste0("Data.table containing the experiment plan, including",
                                " a column with the link to the folder with each model's",
                                " results")),
    createsOutput(objectName = "experimentDatasets", objectClass = "list", 
                  desc = paste0("List of data.tables containing the specific datasets ",
                                " for each experiment planned")),
    createsOutput(objectName = "fittedModelsPaths", objectClass = "list", 
                  desc = paste0("Named list of saved model object paths",
                                " generated by the experiment, named with each experiment")),
    createsOutput("preparedDataFinal", "data.table", 
                 paste0("Data table containing Dataset of raw ",
                        "features after preparation (interactions added, etc.) ",
                        "This is generally done by another module and copied here.",
                        "This should be restructured at some point to improve modularity."))
  )
))

doEvent.caribouNN = function(sim, eventTime, eventType) {
  switch(
    eventType,
    init = {
      
      # schedule future event(s)
      sim <- scheduleEvent(sim, time(sim), "caribouNN", "prepareExperiment")
      sim <- scheduleEvent(sim, time(sim), "caribouNN", "trainExperiment")
      sim <- scheduleEvent(sim, time(sim), "caribouNN", "predictExperiment")
      sim <- scheduleEvent(sim, time(sim), "caribouNN", "compareExperiment")
      sim <- scheduleEvent(sim, time(sim), "caribouNN", "analyseExperiment")
    },
    prepareExperiment = {
      
      # LOAD DATA
      if (all(!is.null(sim$preparedData$preparedDataFinal),
              is.null(sim$preparedDataFinal)))
        sim$preparedDataFinal <- sim$preparedData$preparedDataFinal
      # TODO need to make checks for the data here!
      if (is.null(sim$preparedDataFinal))
        stop("preparedDataFinal is NULL. Debug!")
      
      # 1. GENERATE EXPERIMENT PLAN
      #TODO Make the arguments as parameters
      experimentPlanPath <- file.path(outputPath(sim), "experimentalDesignFinal.csv")
      if (all(P(sim)$useSavedPlan,
              file.exists(experimentPlanPath))){
        message("Final experiment plan found and being used...")
        sim$experimentPlan <- fread(experimentPlanPath)
      } else {
        message("Final experiment plan being created...")
        sim$experimentPlan <- generateExperimentPlan(startYear = 2008,
                                                     endYear = 2022,
                                                     numberOfCovariatesList = c(2, 5, 10, Inf),
                                                     outputPath = file.path(outputPath(sim), 
                                                                            paste0("experimentalDesign",
                                                                                   format(Sys.Date(),
                                                                                          "%d%b%y"),
                                                                                   ".csv")))
        # NOTE: in experimentPlan we need to swap 2008 for 2007 because we do not have data for 
        # 2008, but do for 2007
        # This way we avoid many "empty" models and are still using the same amount of years 
        # for the analysis
        sim$experimentPlan[trainStartYear == 2008, trainStartYear := 2007]
        sim$experimentPlan[trainEndYear == 2008, trainEndYear := 2007]
        sim$experimentPlan[valStartYear == 2008, valStartYear := 2007]
        sim$experimentPlan[valEndYear == 2008, valEndYear := 2007]
        sim$experimentPlan[testStartYear == 2008, testStartYear := 2007]
        sim$experimentPlan[testEndYear == 2008, testEndYear := 2007]

        # 2. ADD CAPPING TO CONTROL SAMPLE SIZES
        sim$experimentPlan <- addSamplingCaps(preparedDataFinal = sim$preparedDataFinal, 
                                              experimentPlan = sim$experimentPlan,
                                              outDir = outputPath(sim))
        
        verifySamplingMath(experimentPlan = sim$experimentPlan, 
                           preparedDataFinal = sim$preparedDataFinal, 
                           nChecks = 250)
        
        # 3. SAVE THE EXPERIMENT PLAN
        fwrite(sim$experimentPlan, experimentPlanPath)
      }
      
      if (!P(sim)$modComplex %in% c("all", sim$experimentPlan$numberOfCovariates)){
        pt <- paste(c("all", unique(experimentPlan$numberOfCovariates)), collapse = ", ")
        stop(paste0("modComplex = ", P(sim)$modComplex,". The only available values are: ", pt))
      }
      
     },
    trainExperiment = {

      sim$fittedModelsPaths <- theExperiment(preparedData = sim$preparedDataFinal, 
                                         batchSize = P(sim)$batchSize,
                                         epoch = P(sim)$epoch,
                                         featurePriority = sim$featurePriority,
                                         learningRate =  P(sim)$learningRate,
                                         outputDir = checkPath(file.path(outputPath(sim), 
                                                                         "testedModels"), 
                                                               create = TRUE),
                                         experimentPlan = sim$experimentPlan,
                                         reRunModels = P(sim)$reRunModels,
                                         reRunDataset = P(sim)$reRunDataset,
                                         modComplex = P(sim)$modComplex,
                                         maxClu = P(sim)$maxClu,
                                         useFuture = P(sim)$useFuture)
    },
    predictExperiment = {
      
    },
    compareExperiment = {
      
    },
    analyseExperiment = {
      
    },
    warning(noEventWarning(sim))
  )
  return(invisible(sim))
}

.inputObjects <- function(sim) {
  
  dPath <- asPath(getOption("reproducible.destinationPath", dataPath(sim)), 1)
  message(currentModule(sim), ": using dataPath '", dPath, "'.")
  if (!suppliedElsewhere("preparedDataFinal", sim = sim)){
    if(!suppliedElsewhere("extractedVariables", sim = sim))
      stop("No defaults have been implemented yet...Please run caribouNN_Gobal")
  }
  if (!suppliedElsewhere("featurePriority", sim = sim)){
    sim$featurePriority <- fread("inputs/featureTable.csv")
  }
  return(invisible(sim))
}
